<application>
  <component name="RecentProjectsManager">
    <option name="recentPaths">
      <list>
        <option value="D:/TEST/layput" />
        <option value="D:/AD/kaola100MVp" />
        <option value="D:/AD/yue" />
        <option value="D:/TEST/VLayout" />
        <option value="D:/AD/kaola100" />
        <option value="D:/TEST/LoginArchitecture-master" />
        <option value="D:/AD/yuej" />
        <option value="D:/AD/yuejuan" />
        <option value="D:/AD/layput" />
        <option value="D:/FFmpeg/BigImageViewer-master" />
        <option value="D:/FFmpeg/FrescoImageViewer-master" />
        <option value="D:/FFmpeg/PhotoPick" />
        <option value="D:/FFmpeg/SvgView" />
        <option value="D:/FFmpeg/button" />
        <option value="D:/FFmpeg/Universal-Image-Loader" />
        <option value="D:/FFmpeg/RxGalleryFinal" />
        <option value="D:/AD/zxingdome" />
        <option value="D:/FFmpeg/ImagePreview" />
        <option value="D:/FFmpeg/BaseRecyclerViewAdapterHelper" />
        <option value="D:/AD/netWork" />
        <option value="D:/FFmpeg/SVGDemo" />
        <option value="D:/FFmpeg/ChinaMap" />
        <option value="D:/FFmpeg/ChinaMapView" />
        <option value="D:/FFmpeg/ser" />
        <option value="D:/FFmpeg/model" />
        <option value="D:/FFmpeg/playPCM" />
        <option value="D:/AD/EbookM" />
        <option value="D:/AD/incSVG" />
        <option value="D:/FFmpeg/SwipeRecyclerView" />
        <option value="D:/FFmpeg/SuperEasyRefreshLayout-master" />
        <option value="D:/AD/EbookMvp" />
        <option value="D:/AD/vlayout2" />
        <option value="D:/AD/permission" />
        <option value="D:/FFmpeg/android-ndk-master/hello-gl2" />
        <option value="D:/FFmpeg/AndroidOpenGLDemo-master" />
        <option value="D:/FFmpeg/JiaoXueKeYan" />
        <option value="D:/FFmpeg/FFmpegYUVRGBOpenGL" />
        <option value="D:/FFmpeg/wlplayer" />
        <option value="D:/FFmpeg/android-ndk-master/gles3jni" />
        <option value="D:/FFmpeg/ebook" />
        <option value="D:/AD/网校安卓/EbookMvp" />
        <option value="D:/AD/EbookMv" />
        <option value="D:/AD/FFmpegDemo" />
        <option value="D:/FFmpeg/FFMpegNativeWindow" />
        <option 